// French translation of FaceTec's own OCR Confirmation Screen template (group/field labels shown
// on the "Examiner et confirmer" screen — the one listing every field OCR'd off the document for
// the user to check). `fieldKey`/`groupKey` are FaceTec's own internal identifiers, left as-is;
// only the user-facing `groupFriendlyName`/`fieldFriendlyName`/`uiFieldDescriptionText` strings
// are translated. Structure copied from the vendored SDK's own template at
// FaceTecSDK-browser-10.1.18/sample-app-resources/FaceTec_OCR_Customization.json — every group and
// field FaceTec supports, translated, so no field silently falls back to English regardless of
// which document type/field combination FaceTec actually OCR's off a given ID.
export const faceTecOcrLocalizationFr = {
  groups: [
    {
      groupKey: 'userInfo',
      groupFriendlyName: 'Vos informations',
      fields: [
        { fieldKey: 'profession', fieldFriendlyName: 'Profession', uiFieldDescriptionText: 'Profession' },
        { fieldKey: 'lastName', fieldFriendlyName: 'Nom', uiFieldDescriptionText: 'Nom' },
        { fieldKey: 'parentsNames', fieldFriendlyName: 'Noms des parents', uiFieldDescriptionText: 'Noms des parents' },
        { fieldKey: 'placeOfBirth', fieldFriendlyName: 'Lieu de naissance', uiFieldDescriptionText: 'Lieu de naissance' },
        { fieldKey: 'telephoneNumber', fieldFriendlyName: 'Numéro de téléphone', uiFieldDescriptionText: 'Numéro de téléphone' },
        { fieldKey: 'fatherLastName', fieldFriendlyName: 'Nom du père', uiFieldDescriptionText: 'Nom du père' },
        { fieldKey: 'givenName', fieldFriendlyName: 'Prénom usuel', uiFieldDescriptionText: 'Prénom usuel' },
        { fieldKey: 'fullName', fieldFriendlyName: 'Nom complet', uiFieldDescriptionText: 'Nom complet' },
        { fieldKey: 'dateOfBirth', fieldFriendlyName: 'Date de naissance', uiFieldDescriptionText: 'Date de naissance' },
        { fieldKey: 'placeOfBirthLine2', fieldFriendlyName: 'Lieu de naissance (ligne 2)', uiFieldDescriptionText: 'Lieu de naissance (ligne 2)' },
        { fieldKey: 'spouse', fieldFriendlyName: 'Conjoint(e)', uiFieldDescriptionText: 'Conjoint(e)' },
        { fieldKey: 'firstName', fieldFriendlyName: 'Prénom', uiFieldDescriptionText: 'Prénom' },
        { fieldKey: 'middleInitial', fieldFriendlyName: 'Initiale du second prénom', uiFieldDescriptionText: 'Initiale du second prénom' },
        { fieldKey: 'nationality', fieldFriendlyName: 'Nationalité', uiFieldDescriptionText: 'Nationalité' },
        { fieldKey: 'fatherFirstName', fieldFriendlyName: 'Prénom du père', uiFieldDescriptionText: 'Prénom du père' },
        { fieldKey: 'motherFirstName', fieldFriendlyName: 'Prénom de la mère', uiFieldDescriptionText: 'Prénom de la mère' },
        { fieldKey: 'grandfatherFirstName', fieldFriendlyName: 'Prénom du grand-père', uiFieldDescriptionText: 'Prénom du grand-père' },
        { fieldKey: 'motherLastName', fieldFriendlyName: 'Nom de la mère', uiFieldDescriptionText: 'Nom de la mère' },
        { fieldKey: 'employer', fieldFriendlyName: 'Employeur', uiFieldDescriptionText: 'Employeur' },
        { fieldKey: 'middleName', fieldFriendlyName: 'Second prénom', uiFieldDescriptionText: 'Second prénom' },
      ],
    },
    {
      groupKey: 'addressInfo',
      groupFriendlyName: 'Votre adresse',
      fields: [
        { fieldKey: 'zipCode', fieldFriendlyName: 'Code postal', uiFieldDescriptionText: 'Code postal' },
        { fieldKey: 'country', fieldFriendlyName: 'Pays', uiFieldDescriptionText: 'Pays' },
        { fieldKey: 'employerAddress', fieldFriendlyName: "Adresse de l'employeur", uiFieldDescriptionText: "Adresse de l'employeur" },
        { fieldKey: 'address3', fieldFriendlyName: 'Adresse (ligne 3)', uiFieldDescriptionText: 'Adresse (ligne 3)' },
        { fieldKey: 'address2', fieldFriendlyName: 'Adresse (ligne 2)', uiFieldDescriptionText: 'Adresse (ligne 2)' },
        { fieldKey: 'city', fieldFriendlyName: 'Ville', uiFieldDescriptionText: 'Ville' },
        { fieldKey: 'address1', fieldFriendlyName: 'Adresse (ligne 1)', uiFieldDescriptionText: 'Adresse (ligne 1)' },
        { fieldKey: 'commune', fieldFriendlyName: 'Commune', uiFieldDescriptionText: 'Commune' },
        { fieldKey: 'county', fieldFriendlyName: 'Comté', uiFieldDescriptionText: 'Comté' },
        { fieldKey: 'province', fieldFriendlyName: 'Province', uiFieldDescriptionText: 'Province' },
        { fieldKey: 'schoolAddressLine3', fieldFriendlyName: "Adresse de l'école (ligne 3)", uiFieldDescriptionText: "Adresse de l'école (ligne 3)" },
        { fieldKey: 'schoolAddressLine2', fieldFriendlyName: "Adresse de l'école (ligne 2)", uiFieldDescriptionText: "Adresse de l'école (ligne 2)" },
        { fieldKey: 'schoolAddressLine1', fieldFriendlyName: "Adresse de l'école (ligne 1)", uiFieldDescriptionText: "Adresse de l'école (ligne 1)" },
        { fieldKey: 'council', fieldFriendlyName: 'Conseil', uiFieldDescriptionText: 'Conseil' },
        { fieldKey: 'district', fieldFriendlyName: 'District', uiFieldDescriptionText: 'District' },
        { fieldKey: 'state', fieldFriendlyName: 'État', uiFieldDescriptionText: 'État' },
        { fieldKey: 'municipalityOfResidence', fieldFriendlyName: 'Commune de résidence', uiFieldDescriptionText: 'Commune de résidence' },
        { fieldKey: 'addressLine4', fieldFriendlyName: 'Adresse (ligne 4)', uiFieldDescriptionText: 'Adresse (ligne 4)' },
        { fieldKey: 'village', fieldFriendlyName: 'Village', uiFieldDescriptionText: 'Village' },
        { fieldKey: 'region', fieldFriendlyName: 'Région', uiFieldDescriptionText: 'Région' },
        { fieldKey: 'territory', fieldFriendlyName: 'Territoire', uiFieldDescriptionText: 'Territoire' },
      ],
    },
    {
      groupKey: 'secondaryUserInfo',
      groupFriendlyName: 'Traits physiques et divers',
      fields: [
        { fieldKey: 'hair', fieldFriendlyName: 'Cheveux', uiFieldDescriptionText: 'Cheveux' },
        { fieldKey: 'pollingStationCode', fieldFriendlyName: 'Code du bureau de vote', uiFieldDescriptionText: 'Code du bureau de vote' },
        { fieldKey: 'sex', fieldFriendlyName: 'Sexe', uiFieldDescriptionText: 'Sexe' },
        { fieldKey: 'complexion', fieldFriendlyName: 'Teint', uiFieldDescriptionText: 'Teint' },
        { fieldKey: 'pollingStation', fieldFriendlyName: 'Bureau de vote', uiFieldDescriptionText: 'Bureau de vote' },
        { fieldKey: 'weight', fieldFriendlyName: 'Poids', uiFieldDescriptionText: 'Poids' },
        { fieldKey: 'remarksLine3', fieldFriendlyName: 'Remarques (ligne 3)', uiFieldDescriptionText: 'Remarques (ligne 3)' },
        { fieldKey: 'bloodType', fieldFriendlyName: 'Groupe sanguin', uiFieldDescriptionText: 'Groupe sanguin' },
        { fieldKey: 'remarksLine2', fieldFriendlyName: 'Remarques (ligne 2)', uiFieldDescriptionText: 'Remarques (ligne 2)' },
        { fieldKey: 'eyes', fieldFriendlyName: 'Yeux', uiFieldDescriptionText: 'Yeux' },
        { fieldKey: 'remarksLine1', fieldFriendlyName: 'Remarques (ligne 1)', uiFieldDescriptionText: 'Remarques (ligne 1)' },
        { fieldKey: 'height', fieldFriendlyName: 'Taille', uiFieldDescriptionText: 'Taille' },
      ],
    },
    {
      groupKey: 'customFields',
      groupFriendlyName: 'Informations complémentaires',
      fields: [
        { fieldKey: 'customField5', fieldFriendlyName: 'Champ personnalisé 5', uiFieldDescriptionText: 'Champ personnalisé 5' },
        { fieldKey: 'customField1', fieldFriendlyName: 'Champ personnalisé 1', uiFieldDescriptionText: 'Champ personnalisé 1' },
        { fieldKey: 'customField2', fieldFriendlyName: 'Champ personnalisé 2', uiFieldDescriptionText: 'Champ personnalisé 2' },
        { fieldKey: 'customField3', fieldFriendlyName: 'Champ personnalisé 3', uiFieldDescriptionText: 'Champ personnalisé 3' },
        { fieldKey: 'customField4', fieldFriendlyName: 'Champ personnalisé 4', uiFieldDescriptionText: 'Champ personnalisé 4' },
      ],
    },
    {
      groupKey: 'idInfo',
      groupFriendlyName: "Détails de la pièce d'identité",
      fields: [
        { fieldKey: 'idNumber', fieldFriendlyName: "N° de la pièce d'identité", uiFieldDescriptionText: "N° de la pièce d'identité" },
        { fieldKey: 'civilStatus', fieldFriendlyName: 'Situation matrimoniale', uiFieldDescriptionText: 'Situation matrimoniale' },
        { fieldKey: 'placeOfIssue', fieldFriendlyName: 'Lieu de délivrance', uiFieldDescriptionText: 'Lieu de délivrance' },
        { fieldKey: 'dateOfExpiration', fieldFriendlyName: "Date d'expiration", uiFieldDescriptionText: "Date d'expiration" },
        { fieldKey: 'countryCode', fieldFriendlyName: 'Code pays', uiFieldDescriptionText: 'Code pays' },
        { fieldKey: 'authorityLine2', fieldFriendlyName: 'Autorité de délivrance (ligne 2)', uiFieldDescriptionText: 'Autorité de délivrance (ligne 2)' },
        { fieldKey: 'end', fieldFriendlyName: 'Mentions', uiFieldDescriptionText: 'Mentions' },
        { fieldKey: 'barcode', fieldFriendlyName: 'Code-barres', uiFieldDescriptionText: 'Code-barres' },
        { fieldKey: 'class', fieldFriendlyName: 'Catégorie', uiFieldDescriptionText: 'Catégorie' },
        { fieldKey: 'typeOfPermitLine1', fieldFriendlyName: 'Type de permis (ligne 1)', uiFieldDescriptionText: 'Type de permis (ligne 1)' },
        { fieldKey: 'typeOfPermitLine2', fieldFriendlyName: 'Type de permis (ligne 2)', uiFieldDescriptionText: 'Type de permis (ligne 2)' },
        { fieldKey: 'permitValidFrom', fieldFriendlyName: 'Permis valide à partir de', uiFieldDescriptionText: 'Permis valide à partir de' },
        { fieldKey: 'restrictions', fieldFriendlyName: 'Restrictions', uiFieldDescriptionText: 'Restrictions' },
        { fieldKey: 'passportType', fieldFriendlyName: 'Type de passeport', uiFieldDescriptionText: 'Type de passeport' },
        { fieldKey: 'bookletNumber', fieldFriendlyName: 'Numéro de carnet', uiFieldDescriptionText: 'Numéro de carnet' },
        { fieldKey: 'dateOfIssue', fieldFriendlyName: 'Date de délivrance', uiFieldDescriptionText: 'Date de délivrance' },
        { fieldKey: 'idNumber2', fieldFriendlyName: "N° d'identité secondaire", uiFieldDescriptionText: "N° d'identité secondaire" },
        { fieldKey: 'barcode2', fieldFriendlyName: 'Code-barres 2', uiFieldDescriptionText: 'Code-barres 2' },
        { fieldKey: 'idNumber3', fieldFriendlyName: "N° d'identité tertiaire", uiFieldDescriptionText: "N° d'identité tertiaire" },
        { fieldKey: 'issuingAuthority', fieldFriendlyName: 'Autorité de délivrance', uiFieldDescriptionText: 'Autorité de délivrance' },
        { fieldKey: 'cpfNumber', fieldFriendlyName: 'Numéro CPF', uiFieldDescriptionText: 'Numéro CPF' },
        { fieldKey: 'mrzLine3', fieldFriendlyName: 'MRZ 3', uiFieldDescriptionText: 'MRZ 3' },
        { fieldKey: 'firstIssue', fieldFriendlyName: 'Première délivrance', uiFieldDescriptionText: 'Première délivrance' },
        { fieldKey: 'mrzLine1', fieldFriendlyName: 'MRZ 1', uiFieldDescriptionText: 'MRZ 1' },
        { fieldKey: 'mrzLine2', fieldFriendlyName: 'MRZ 2', uiFieldDescriptionText: 'MRZ 2' },
        { fieldKey: 'cardAccessNumber', fieldFriendlyName: "Numéro d'accès à la carte (CAN)", uiFieldDescriptionText: "Numéro d'accès à la carte (CAN)" },
      ],
    },
  ],
};
